/*
 * This file is part of Partyflow.
 *
 * Partyflow is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Partyflow is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with Partyflow.
 *
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.unascribed.partyflow.logic;

import java.util.Arrays;

import com.unascribed.partyflow.config.TranscodeFormat.ReplayGainData;

import com.google.common.collect.ImmutableMap;

public enum SpecialTrack {
	/**
	 * One second of silence. Used to test codec support in browsers.
	 */
	TEST_TRACK("__testtrack", "Test Track", "Autogenerated", 0, new ReplayGainData(0, 0, 0, 0)),
	/**
	 * A fun CC-BY tracker tune I found randomly on ModArchive. Used a tracker tune for size, as I
	 * don't have to feel bad about bloating the jar with an entire multi-megabyte song — instead
	 * it's just 4K when compressed.
	 */
	SAMPLE_SONG("__samplesong", "Something Sinister", "ant512", 2019, new ReplayGainData(-6.3, -6.3, 0.000024, 0.000024)),
	;
	
	public static final ImmutableMap<String, SpecialTrack> BY_SLUG = Arrays.stream(values())
			.collect(ImmutableMap.toImmutableMap(SpecialTrack::slug, o -> o));
	
	private final String slug, title, artist;
	private final int year;
	private final ReplayGainData rg;
	
	SpecialTrack(String slug, String title, String artist, int year, ReplayGainData rg) {
		this.slug = slug;
		this.title = title;
		this.artist = artist;
		this.year = year;
		this.rg = rg;
	}

	public static ImmutableMap<String, SpecialTrack> getBySlug() {
		return BY_SLUG;
	}

	public String slug() {
		return slug;
	}

	public String title() {
		return title;
	}

	public String artist() {
		return artist;
	}
	
	public int year() {
		return year;
	}

	public ReplayGainData rg() {
		return rg;
	}
	
}
