package com.unascribed.partyflow.logic.permission;

/* AUTOGENERATED - DO NOT EDIT */
public final class Permission {
	private Permission() {}

	public static final class admin {
		private admin() {}

		/** Allow modifying the behavior of the Partyflow instance itself. */
		public static final PermissionNode administrate = PermissionNode.ADMIN$ADMINISTRATE;
	}

	public static final class moderate {
		private moderate() {}

		/** Allow other permissions to apply to releases other than the user's own. */
		public static final PermissionNode bypass_ownership = PermissionNode.MODERATE$BYPASS_OWNERSHIP;
	}

	public static final class release {
		private release() {}

		/** Allow creation of new releases. */
		public static final PermissionNode create = PermissionNode.RELEASE$CREATE;
		/** Allow deletion of a user's own releases. */
		public static final PermissionNode delete = PermissionNode.RELEASE$DELETE;

		public static final class track {
			private track() {}

			/** Allow addition of new tracks to a user's own releases. */
			public static final PermissionNode add = PermissionNode.RELEASE$TRACK$ADD;
		}
	}
}
